# Generated by Django 5.0.1 on 2024-02-17 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='aboutcont',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_dis', models.TextField()),
                ('about_title', models.TextField()),
                ('image', models.ImageField(null=True, upload_to='')),
            ],
        ),
    ]
